### ISSUE TITLE
Startup file and link script files for GCC

### ISSUE THREAD

**Issue by yuanye0814** [CommunityGD32Cores/GD32Firmware#1]
For GD32F4xx models, where is the startup file and link script files used by GCC?

**Comment by maxgerhardt** [comment]
Gigadevice doesn't provide them in the regular firmware downloads, only startup files targeting the IAR and ARM compiler as seem [here](https://github.com/CommunityGD32Cores/GD32Firmware/tree/main/GD32F4xx/CMSIS/GD/GD32F4xx/Source).

We had to write a [converter script](https://github.com/CommunityGD32Cores/platform-gd32/tree/main/misc/scripts) to get GCC compatible startup files: https://github.com/CommunityGD32Cores/gd32-pio-spl-package/tree/main/gd32/cmsis/startup_files.

This is higly inconvenient, but this repo is just dumping what GigaDevice gives out.

**Comment by maxgerhardt** [comment]
And of course, using these startup file goes hand-in-hand with using GCC linkerfiles. The **template we have created** for that is in https://github.com/CommunityGD32Cores/gd32-pio-spl-package/blob/main/platformio/ldscripts/tpl/linker.tpl, `$ram` etc has to be replaced with actual values, e.g., `256K`, et cetera. For example, for a GD32F407VG, ram= 128K , ccram = 64K, flash = 1024K, as can e.g. be seen from our [device info files](https://github.com/CommunityGD32Cores/platform-gd32/blob/main/boards/genericGD32F407VG.json).

If you want to try out GCC based compilation, you might be better of just trying an SPL blinky project from https://github.com/CommunityGD32Cores/gd32-pio-projects/tree/main/gd32-spl-blinky.

**Comment by yuanye0814** [comment]
Thank you for your reply, very useful information！
